# Generated by Django 6.0.3 on 2026-04-07 14:29

from django.db import migrations

def assign_mp_admin_blog(apps, schema_editor):
    Blog = apps.get_model('blogs', 'Blog')
    User = apps.get_model('auth', 'User')
    try:
        mp_admin = User.objects.get(username='mp_admin')
        blog = Blog.objects.get(title='mp_admin_blog')
        blog.owner = mp_admin
        blog.save()
    except (User.DoesNotExist, Blog.DoesNotExist, Exception):
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_owner'),
    ]

    operations = [
        migrations.RunPython(assign_mp_admin_blog),
    ]
